### ISSUE TITLE
URL to nodejs buildpack tgz failed

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/multi-buildpack#8]
### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.109.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "f61c0d28-5d9c-4e15-a26f-f8f42129e2e4"
}
cf version 6.36.1+e3799ad7e.2018-04-04
```

### What version of the buildpack you are using?

Latest via git/https

```yaml
applications:
- name: ghost
  buildpack: https://github.com/cloudfoundry/multi-buildpack
```

### If you were attempting to accomplish a task, what was it you were attempting to do?

I was migrating from using nodejs buildpack tgz directly, to using it via multi-buildpack but staging failed.

My original manifest.yml:

```yaml
applications:
- name: ghost
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.6.21/nodejs-buildpack-v1.6.21.zip
```

I created `multi-buildpack.yml`:

```yaml
buildpacks:
- https://github.com/cloudfoundry/apt-buildpack
- https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.6.21/nodejs-buildpack-v1.6.21.zip
```

When I `cf push` it failed:

```
Staging app and tracing logs...
   Downloaded buildpack `https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.6.21/nodejs-buildpack-v1.6.21.zip` (3.8M)
   -----> Running go build supply
   .
   ./final
   ./final/final
   ./final/1986c11e5045899f72e33ebceb13b732
   -----> Apt Buildpack version 0.1.2
   -----> Adding apt keys
   gpg: key 535EAEC4: public key "Stark & Wayne Bot (Created by CI) <drnic+bot@starkandwayne.com>" imported
   gpg: Total number processed: 1
   gpg:               imported: 1  (RSA: 1)
   -----> Adding apt repos
   -----> Updating apt cache
   -----> Downloading apt packages
   -----> Installing apt packages
   -----> Multi Buildpack version 1.0.3
   -----> Installing binaries
          engines.node (package.json): ^6.9.0 || ^8.9.0
          engines.npm (package.json): unspecified (use default)
          **ERROR** Unable to install node: no match found for ^6.9.0 || ^8.9.0 in []
Error staging application: App staging failed in the buildpack compile phase
FAILED
```

### What did you expect to happen?

The runtime nodejs buildpack should have worked as it previously did without multi-buildpack.

### Workaround

The following worked, but the URL to tgz didn't.

```yaml
buildpacks:
- https://github.com/cloudfoundry/apt-buildpack
- https://github.com/cloudfoundry/nodejs-buildpack#v1.6.21
```

**Comment by tylerphelan** [comment]
@drnic I tried using the .zip link with one of our fixtures and the same node version (`^6.9.0 || ^8.9.0`) and it worked. Could you provide an example failing app for us to investigate further?

Also, just to let you know, we are trying to move to [platform multi-buildpack support](https://docs.cloudfoundry.org/buildpacks/use-multiple-buildpacks.html) and away from the system multi-buildpack.

**Comment by drnic** [comment]
What’s the ETA for “cf v3-push” (built in multi buildpack) to be the default?

If this issue doesn’t appear for you then I’ll close this as a one off anomaly until it turns up again.

**Comment by sclevine** [comment]
The cf CLI team is actively working to backport the platform multi-buildpack workflow to the current `cf push` command, so that we won't have to wait for the v3 API to become default to use it.
https://www.pivotaltracker.com/n/projects/892938/search?q=label%3A%22multiple-buildpacks%22

**Comment by drnic** [comment]
Awesome

________________________________
